name: hello-env
channels:
    - defaults
    - conda-forge
    - anaconda

dependencies:
    - python=3.9
    - pip=22.3

    - numpy=1.23
    - scipy=1.10
    - matplotlib=3.6
    - jupyterlab=3.5
    - ipynbname=2021.3
    - pytest=7.1
    - pip:
        # - <some package only available on PyPI>
        - -e .  # build local hello_python package
