# This workflow will install Python dependencies, run tests and lint with a single version of Python.
# It will use conda for dependency management, see 
# https://autobencoder.com/2020-08-24-conda-actions/

name: Python Package Test Using Anaconda

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: hello-env
        environment-file: environment.yml
        python-version: 3.9
    # - name: Install dependencies
    #   run: |
    #     # $CONDA is an environment variable pointing to the root of the miniconda directory
    #     $CONDA/bin/conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest .
